var annotated_dup =
[
    [ "AdcConfig_t", "struct_adc_config__t.html", "struct_adc_config__t" ],
    [ "AdcData_t", "struct_adc_data__t.html", "struct_adc_data__t" ],
    [ "CanConfig_t", "struct_can_config__t.html", "struct_can_config__t" ],
    [ "CanFilterConfig_t", "struct_can_filter_config__t.html", "struct_can_filter_config__t" ],
    [ "CanMessage_t", "struct_can_message__t.html", "struct_can_message__t" ],
    [ "CanMessageHeader_t", "struct_can_message_header__t.html", "struct_can_message_header__t" ],
    [ "DacConfig_t", "struct_dac_config__t.html", "struct_dac_config__t" ],
    [ "EfmiEraseConfig_t", "struct_efmi_erase_config__t.html", "struct_efmi_erase_config__t" ],
    [ "ExtIntConfig_t", "struct_ext_int_config__t.html", "struct_ext_int_config__t" ],
    [ "Frequency_t", "struct_frequency__t.html", "struct_frequency__t" ],
    [ "GpioBankConfig_t", "struct_gpio_bank_config__t.html", "struct_gpio_bank_config__t" ],
    [ "GpioConfig_t", "struct_gpio_config__t.html", "struct_gpio_config__t" ],
    [ "I2cConfig_t", "struct_i2c_config__t.html", "struct_i2c_config__t" ],
    [ "PeriodicHWTimerConfig_t", "struct_periodic_h_w_timer_config__t.html", "struct_periodic_h_w_timer_config__t" ],
    [ "PeripheralConfig_t", "struct_peripheral_config__t.html", "struct_peripheral_config__t" ],
    [ "PortPin_t", "struct_port_pin__t.html", "struct_port_pin__t" ],
    [ "PwmConfig_t", "struct_pwm_config__t.html", "struct_pwm_config__t" ],
    [ "QeiConfig_t", "struct_qei_config__t.html", "struct_qei_config__t" ],
    [ "RtcConfig_t", "struct_rtc_config__t.html", "struct_rtc_config__t" ],
    [ "RtcDateTime_t", "struct_rtc_date_time__t.html", "struct_rtc_date_time__t" ],
    [ "SpiConfig_t", "struct_spi_config__t.html", "struct_spi_config__t" ],
    [ "TimeInterval_t", "struct_time_interval__t.html", "struct_time_interval__t" ],
    [ "UartConfig_t", "struct_uart_config__t.html", "struct_uart_config__t" ],
    [ "WdtConfig_t", "struct_wdt_config__t.html", "struct_wdt_config__t" ]
];